import type { Metadata } from "next";
import "@/styles/global.scss";

import ThemeProviders from "@/providers/ThemeProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white-950 dark:bg-black-500 p-3 mx-auto lg:max-w-[1440px]">
        <ThemeProviders>{children}</ThemeProviders>
      </body>
    </html>
  );
}
